[package]
name = "bad_epstein"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
png = { version = "0.18.0-rc" }
image = "0.25.9"
image-compare = "0.5.0"
tokio = { version = "1.48.0", features = ["full"] }
rayon = "1.11.0"
